
services: 
   backend: 
      build: 
         context: .
         dockerfile: Dockerfile
      ports: 
         - "5000:5000"
      volumes: 
         - .:/app
      environment: 
         - DATABASE_URL= mongodb://mongo:27017/warsStarDB
         - DEBUG=True 
   mongodb: 
      image: mongo:latest
      ports: 
         - "27017:27017"
      volumes: 
         - mongo_data:/data/
    
volumes: 
   mongo_data: 
      